import { useState } from "react";
import { motion } from "framer-motion";
import { Download, FileText, FileCode } from "lucide-react";
import type { AnalysisResult } from "@/lib/mockAnalysis";

interface Props {
  data: AnalysisResult;
}

function generateMarkdownReport(data: AnalysisResult): string {
  const s = data.summary;
  const topFiles = [...data.files]
    .sort((a, b) => (b.technicalDebt + b.cognitiveDebt) - (a.technicalDebt + a.cognitiveDebt))
    .slice(0, 5);

  const avgMetrics = data.files.reduce(
    (acc, f) => {
      for (const k of Object.keys(f.metrics) as (keyof typeof f.metrics)[]) {
        acc[k] = (acc[k] || 0) + f.metrics[k];
      }
      return acc;
    },
    {} as Record<string, number>
  );
  for (const k of Object.keys(avgMetrics)) {
    avgMetrics[k] = Math.round((avgMetrics[k] / data.files.length) * 100) / 100;
  }

  return `# 📊 AI Debt Analysis Report: ${data.repoName}

## Overview
| Metric | Value |
|--------|-------|
| Total Files Analyzed | ${data.totalFiles} |
| Language | ${data.language || 'N/A'} |
| Stars | ${data.stars || 0} |
| High Risk Files | ${s.highRiskFiles} |
| Total Issues | ${s.totalIssues} |

## Key Metrics
| Metric | Score |
|--------|-------|
| Avg AI Likelihood | ${(s.avgAiLikelihood * 100).toFixed(1)}% |
| Avg Technical Debt | ${(s.avgTechnicalDebt * 100).toFixed(1)}% |
| Avg Cognitive Debt | ${(s.avgCognitiveDebt * 100).toFixed(1)}% |

## 🤖 AI Code Analysis
AI-generated code is detected using 5 research-inspired metrics:
- **SUS** (Structural Uniformity Score): ${avgMetrics.sus?.toFixed(2) || 'N/A'} — similarity across functions
- **TDD** (Token Distribution Divergence): ${avgMetrics.tdd?.toFixed(2) || 'N/A'} — deviation from human token usage
- **PRI** (Pattern Repetition Index): ${avgMetrics.pri?.toFixed(2) || 'N/A'} — repeated logic blocks
- **CRS** (Comment Redundancy Score): ${avgMetrics.crs?.toFixed(2) || 'N/A'} — obvious comment explanations
- **SCS** (Style Consistency Score): ${avgMetrics.scs?.toFixed(2) || 'N/A'} — uniform formatting

**Final AI % = weighted(SUS×0.25 + PRI×0.2 + CRS×0.2 + IAS×0.15 + entropy×0.2)**

## 🔧 Technical Debt Summary
Advanced metrics:
- **CP** (Change Proneness): ${avgMetrics.cp?.toFixed(2) || 'N/A'}
- **TC** (Temporal Complexity): ${avgMetrics.tc?.toFixed(2) || 'N/A'}
- **DDP** (Defect Density Proxy): ${avgMetrics.ddp?.toFixed(2) || 'N/A'}
- **MDS** (Modularity Degradation): ${avgMetrics.mds?.toFixed(2) || 'N/A'}

## 🧠 Cognitive Debt Summary
- **CLI** (Cognitive Load Index): ${avgMetrics.cli?.toFixed(2) || 'N/A'}
- **IAS** (Identifier Ambiguity): ${avgMetrics.ias?.toFixed(2) || 'N/A'}
- **AGS** (Abstraction Gap): ${avgMetrics.ags?.toFixed(2) || 'N/A'}
- **RI** (Readability Index): ${avgMetrics.ri?.toFixed(2) || 'N/A'}
- **CSC** (Context Switching Cost): ${avgMetrics.csc?.toFixed(2) || 'N/A'}

## 🔥 Top Risk Files
${topFiles.map((f, i) => `${i + 1}. **${f.file}** — AI: ${(f.aiLikelihood * 100).toFixed(0)}%, Tech: ${(f.technicalDebt * 100).toFixed(0)}%, Cog: ${(f.cognitiveDebt * 100).toFixed(0)}%
   - Issues: ${f.issues.join(', ')}`).join('\n')}

## 💡 Recommendations
${s.topRefactorTargets.map((f, i) => `${i + 1}. Refactor \`${f}\` — highest combined debt`).join('\n')}

---
*Generated by AI Debt Tracker*
`;
}

function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function ReportDownload({ data }: Props) {
  const [downloading, setDownloading] = useState<string | null>(null);

  const handleDownloadMD = () => {
    setDownloading("md");
    const md = generateMarkdownReport(data);
    downloadFile(md, `${data.repoName.replace("/", "-")}-report.md`, "text/markdown");
    setTimeout(() => setDownloading(null), 1000);
  };

  const handleDownloadJSON = () => {
    setDownloading("json");
    const json = JSON.stringify(data, null, 2);
    downloadFile(json, `${data.repoName.replace("/", "-")}-analysis.json`, "application/json");
    setTimeout(() => setDownloading(null), 1000);
  };

  return (
    <div className="flex items-center gap-2">
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={handleDownloadMD}
        disabled={downloading === "md"}
        className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-card/80 backdrop-blur-sm px-3 py-1.5 text-xs font-medium text-foreground hover:bg-secondary/50 transition-colors disabled:opacity-50"
      >
        <FileText className="h-3 w-3" />
        {downloading === "md" ? "Downloading..." : "Download .md"}
      </motion.button>
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={handleDownloadJSON}
        disabled={downloading === "json"}
        className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-card/80 backdrop-blur-sm px-3 py-1.5 text-xs font-medium text-foreground hover:bg-secondary/50 transition-colors disabled:opacity-50"
      >
        <FileCode className="h-3 w-3" />
        {downloading === "json" ? "Downloading..." : "Download JSON"}
      </motion.button>
    </div>
  );
}
